### ISSUE TITLE
สวัสดีครับ

### ISSUE THREAD

**Issue by poonsak58** [Phonbopit/hello-github#24]
ผมอ่านสอนเรื่อง github จนมาถึงตอน workshop แล้วครับ
ผมงงกับข้อ 4. ที่บอกว่า "แต่ขอแค่ ต้องมีไฟล์ README.md มาด้วย"
ไฟล์นี้คือผมเอามาจากไหนครับ
ขอบคุณครับ

**Comment by Phonbopit** [comment]
สวัสดีครับ new file ขึ้นมาใหม่ได้เลยครับ ลองดูตัวอย่างโฟลเดอร์ของเพื่อนๆคนอื่นดูครับ จะมีไฟล์  `README.md` และไฟล์อื่นๆอะไรก็ได้ไม่บังคับ หรือจะก็อปปี้จาก [ตัวอย่างของผม มีไฟล์ `README.md` กับ `profile.js`](https://github.com/Phonbopit/hello-github/tree/master/phonbopit) ก็ได้

**Comment by Phonbopit** [comment]
closed pr #25
