### ISSUE TITLE
สอบถามเรื่องตอน push ครับ

### ISSUE THREAD

**Issue by Gekkouga234** [Phonbopit/hello-github#72]
พอแตก branch มาแล้ว ตอน push ผมต้อง merge กับ ตัว master แล้ว push หรือ ว่า push จาก branch ที่แตกมาครับ

**Comment by Phonbopit** [comment]
แล้วแต่เลยครับ กรณี fork โปรเจ็คมา เราจะแตก branch เพื่อมาทำ feature อะไรซักอย่าง เสร็จแล้วค่อย merge master แล้วถึง push ขึ้นมา เปิด Pull Request มาหา git ต้นฉบับก็ได้ หรือจะ push จาก branch feature แล้วเปิด Pull Request มาก็เหมือนกันครับ
