### ISSUE TITLE
pull requestไม่ได้ครับ

### ISSUE THREAD

**Issue by cpekmutt5845** [Phonbopit/hello-github#75]
![image](https://user-images.githubusercontent.com/24917389/30515089-e9ce0ba8-9b4b-11e7-9dc4-0e0cd9dbfafc.png)

pullไม่ได้ครับ ขึ้นตามรูปเลยครับ ผมแยกทำในbranchใหม่่ชื่อ new_branch
พอผมเข้าไปbranchของผม มันเตือนว่า "This branch is 12 commits ahead, 177 commits behind Phonbopit:master." 
สาเหตุเกิดจากอะไรครับ ขอบคุณครับ

**Comment by Phonbopit** [comment]
ทั้งสอง branch มีโค๊ดที่ไม่ sync กันครับ

**Comment by Phonbopit** [comment]
ตอนแยก `new_branch` ออกมานี่แตกออกมาจาก `master` ที่ sync กับของผมแล้วรึเปล่าครับ? 

แต่ที่สงสัยคือ 177 commits behind นี่เท่ากับจำนวน commit ทั้งหมดของผมเลย ซึ่งดูเหมือนว่า `new_branch` ถูกสร้างมาตอน git init เลย

**Comment by cpekmutt5845** [comment]
pull request ได้แล้วครับ ผมย้ายมาทำในmaster แล้วลบ new_branch ทิ้ง รบกวนเชคไฟล์ที่pullไปด้วยครับ ขอบคุณล่วงหน้าครับ
