### ISSUE TITLE
hacktoberfest

### ISSUE THREAD

**Issue by Phonbopit** [Phonbopit/hello-github#83]
Welcome 😄 

Rule:

1. Fork this repo
2. Create a folder based on your github username
3. Create `README.md` file inside, another file is optional
4. Done!

If you like it, please stared this repo and share to your friends 🎉 

https://hacktoberfest.digitalocean.com/

❤️  Happy Coding

**Comment by WarEnek** [comment]
Done https://github.com/Phonbopit/hello-github/pull/84

**Comment by Phonbopit** [comment]
Always open this issues for people searching with `hacktoberfest` label 😄

**Comment by zzyzy** [comment]
Thanks mate 😃

**Comment by Phonbopit** [comment]
Done
